x-common: &common
  working_dir: /go/src/microservice
  tty: true
  expose:
    - 8080
  depends_on:
    - postgres
  environment:
    - TZ=Asia/Tokyo
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=stockapp
    - POSTGRES_PASSWORD=stockapp
    - POSTGRES_DB=stockapp
  command: sh -c "go run cmd/main.go"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/vhost.d:ro
    environment:
      - DEFAULT_HOST=localhost
    depends_on:
      - service-1
      - service-2
      - service-3
    networks:
      app_network:
        aliases:
          - service-1
          - service-2
          - service-3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=stockapp
      - POSTGRES_PASSWORD=stockapp
      - POSTGRES_DB=stockapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  service-1:
    <<: *common
    build:
      context: "./service-1"
    volumes:
      - ./service-1:/go/src/microservice
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    networks:
      - app_network

  service-2:
    <<: *common
    build:
      context: "./service-2"
    volumes:
      - ./service-2:/go/src/microservice
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    networks:
      - app_network

  service-3:
    <<: *common
    build:
      context: "./service-3"
    volumes:
      - ./service-3:/go/src/microservice
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
