FROM alpine:3.18 as tzdata
RUN apk --no-cache add tzdata

FROM golang:1.23.4-alpine

COPY --from=tzdata /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ='Asia/Tokyo'
ENV LANG='ja_JP.UTF-8'

# 必要なパッケージのインストール
RUN apk add --no-cache gcc musl-dev

# 依存関係のコピーとダウンロード
COPY go.mod go.sum ./
RUN go mod download

# ソースコードのコピー
COPY . .

# アプリケーションのビルドと実行
CMD ["go", "run", "main.go"]
